language: go
sudo: required
env:
  - HUGO_VERSION=0.25.1

install:
  - sudo apt-get install lftp
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz hugo
  - git submodule update --remote

script:
  - ./hugo

after_success:
  - lftp ftp://${USER}:${PASSWD}@home.ustc.edu.cn/ -e "mirror -R ./public /public_html; quit"
